from __future__ import annotations

import json
import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from sqlalchemy import select
from sqlalchemy.orm import Session

from ..database import BACKEND_DIR, SessionLocal
from ..models import Player, PlayerAlias
from .schema_utils import ensure_database_schema

REPORT_PATH = BACKEND_DIR / "reports" / "player_alias_report.json"


def strip_accents(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    return "".join(char for char in normalized if not unicodedata.combining(char))


def strip_punctuation(value: str) -> str:
    return re.sub(r"[^\w\s]", "", value).strip()


def collapse_whitespace(value: str) -> str:
    return re.sub(r"\s+", " ", value).strip()


def initials_alias(name: str) -> str | None:
    parts = name.split()
    if len(parts) < 2:
        return None
    initials = "".join(part[0] for part in parts[:-1] if part)
    if not initials:
        return None
    return f"{initials} {parts[-1]}"


def aliases_for_name(name: str) -> list[tuple[str, str]]:
    candidates = [
        (name, "exact"),
        (name.lower(), "lowercase"),
        (strip_accents(name), "accent_stripped"),
        (strip_punctuation(name), "punctuation_stripped"),
        (strip_punctuation(strip_accents(name)), "accent_and_punctuation_stripped"),
    ]
    initials = initials_alias(strip_punctuation(strip_accents(name)))
    if initials is not None:
        candidates.append((initials, "initials"))

    aliases: list[tuple[str, str]] = []
    seen: set[str] = set()
    for alias, source in candidates:
        alias = collapse_whitespace(alias)
        if not alias or alias in seen:
            continue
        seen.add(alias)
        aliases.append((alias, source))
    return aliases


def build_aliases(db: Session) -> dict[str, Any]:
    report: dict[str, Any] = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "players_processed": 0,
        "aliases_created": 0,
        "aliases_existing": 0,
        "total_aliases": 0,
    }

    existing = {
        (alias.player_id, alias.alias_name)
        for alias in db.scalars(select(PlayerAlias)).all()
    }
    players = db.scalars(select(Player).order_by(Player.id)).all()
    for player in players:
        report["players_processed"] += 1
        for alias_name, source in aliases_for_name(player.display_name):
            key = (player.id, alias_name)
            if key in existing:
                report["aliases_existing"] += 1
                continue
            db.add(
                PlayerAlias(
                    player=player,
                    alias_name=alias_name,
                    source=source,
                    notes="Generated by build_aliases",
                ),
            )
            existing.add(key)
            report["aliases_created"] += 1

    db.commit()
    report["total_aliases"] = len(existing)
    return report


def write_report(report: dict[str, Any], path: Path = REPORT_PATH) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2) + "\n")


def main() -> None:
    ensure_database_schema()
    with SessionLocal() as db:
        report = build_aliases(db)
    write_report(report)
    print(json.dumps(report, indent=2))
    print(f"Player alias report written to {REPORT_PATH}")


if __name__ == "__main__":
    main()
